### PR TITLE
relax the version constraint with m2e core

### PR DESCRIPTION
**Pull request by maroschutte**
update the version range in the dependency with org.eclipse.m2e.\* to [1.0.0,2.0.0)

This will resolve issue #5

### CODE REVIEW

**Comment by maroschutte** [comment]
Thanks Jason, and the CI build did run already too!

http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-cvs/0.13.0/N/0.13.0.201304101743/

**Comment by jvanzyl** [comment]
If it installs for you then we can promote it into the catalog.

**Comment by maroschutte** [comment]
It installs fine, but I want to test it some more tomorrow at work. Will
let you know.
Marcel
Op 10 apr. 2013 19:55 schreef "Jason van Zyl" notifications@github.com
het volgende:

**Comment by jvanzyl** [comment]
Great, thanks!

**Comment by maroschutte** [comment]
Hi Jason,

OK, the new version works in combination with juno SR2 and m2e 1.3.1, so
you can promote it to the m2e catalog.

Marcel

On Wed, Apr 10, 2013 at 8:17 PM, Jason van Zyl notifications@github.comwrote:

> Great, thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sonatype/m2eclipse-cvs/pull/6#issuecomment-16192135
> .

## 

Fotografie
http://schutte.name/

**Pull request merged**
